[package]
name = "pride"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.5.0"
termion = "2.0.1"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

